local LSM = LibStub("LibSharedMedia-3.0")
	 
--StatusBars

LSM:Register("statusbar","Fanatical", [[Interface\Addons\!FanaticalMedia\StatusBars\Fanatical]])
LSM:Register("statusbar","Kait", [[Interface\Addons\!FanaticalMedia\StatusBars\Kait.tga]])
LSM:Register("statusbar","Skullflower", [[Interface\Addons\!FanaticalMedia\StatusBars\Skullflower.tga]])
LSM:Register("statusbar","Skullflower1", [[Interface\Addons\!FanaticalMedia\StatusBars\Skullflower1.tga]])
LSM:Register("statusbar","Skullflower2", [[Interface\Addons\!FanaticalMedia\StatusBars\Skullflower2.tga]])
LSM:Register("statusbar","Skullflower3", [[Interface\Addons\!FanaticalMedia\StatusBars\Skullflower3.tga]])
LSM:Register("statusbar","Skullflower4", [[Interface\Addons\!FanaticalMedia\StatusBars\Skullflower4.tga]])
LSM:Register("statusbar","Skullflower5", [[Interface\Addons\!FanaticalMedia\StatusBars\Skullflower5.tga]])
LSM:Register("statusbar","SkullflowerGradient", [[Interface\Addons\!FanaticalMedia\StatusBars\SkullflowerGradient.tga]])
LSM:Register("statusbar","SkullflowerGradient1", [[Interface\Addons\!FanaticalMedia\StatusBars\SkullflowerGradient1.tga]])
LSM:Register("statusbar","SkullflowerLight", [[Interface\Addons\!FanaticalMedia\StatusBars\SkullflowerLight.tga]])
LSM:Register("statusbar","SkullflowerNeon", [[Interface\Addons\!FanaticalMedia\StatusBars\SkullflowerNeon.tga]])
--Sounds
LSM:Register("sound","Blade", [[Interface\Addons\!FanaticalMedia\Sounds\Blade.ogg]])
LSM:Register("sound","Buffed", [[Interface\Addons\!FanaticalMedia\Sounds\Buffed.ogg]])
LSM:Register("sound","Bullet", [[Interface\Addons\!FanaticalMedia\Sounds\Bullet.ogg]])
LSM:Register("sound","Info", [[Interface\Addons\!FanaticalMedia\Sounds\Info.ogg]])
LSM:Register("sound","Mail", [[Interface\Addons\!FanaticalMedia\Sounds\Mail.ogg]])
LSM:Register("sound","Positive", [[Interface\Addons\!FanaticalMedia\Sounds\Positive.ogg]])
LSM:Register("sound","Thunder", [[Interface\Addons\!FanaticalMedia\Sounds\Thunder.ogg]])
LSM:Register("sound","On You", [[Interface\Addons\!FanaticalMedia\Sounds\OnYou.ogg]])
LSM:Register("sound","Liquid Shriek", [[Interface\Addons\!FanaticalMedia\Sounds\Liquid-SHRIEK.ogg]])
LSM:Register("sound","oTankTaunted", [[Interface\Addons\!FanaticalMedia\Sounds\oTankTaunted.mp3]])
--Fonts
LSM:Register("font","Expressway", [[Interface\Addons\!FanaticalMedia\Fonts\Expressway.TTF]])

--ELVUI mMEDIA TAG

local function mAddStatusbar(name, file)
	LSM:Register("statusbar", name, "Interface\\AddOns\\!FanaticalMedia\\textures\\" .. file)
end

local function mAddBackground(name, file)
	LSM:Register("background", name, "Interface\\AddOns\\!FanaticalMedia\\backgrounds\\" .. file)
end

local function mAddFont(name, file)
	LSM:Register("font", name, "Interface\\AddOns\\!FanaticalMedia\\fonts\\" .. file)
end

local function mAddBorder(name, file)
	LSM:Register("border", name, "Interface\\AddOns\\!FanaticalMedia\\border\\" .. file)
end

mAddStatusbar("mMediaTag M1", "m1.tga")
mAddStatusbar("mMediaTag M2", "m2.tga")
mAddStatusbar("mMediaTag M3", "m3.tga")
mAddStatusbar("mMediaTag M4", "m4.tga")
mAddStatusbar("mMediaTag M5", "m5.tga")
mAddStatusbar("mMediaTag M6", "m6.tga")
mAddStatusbar("mMediaTag M7", "m7.tga")
mAddStatusbar("mMediaTag M8", "m8.tga")
mAddStatusbar("mMediaTag M9", "m9.tga")
mAddStatusbar("mMediaTag M10", "m10.tga")
mAddStatusbar("mMediaTag M11", "m11.tga")
mAddStatusbar("mMediaTag M12", "m12.tga")
mAddStatusbar("mMediaTag M13", "m13.tga")
mAddStatusbar("mMediaTag M14", "m14.tga")
mAddStatusbar("mMediaTag M15", "m15.tga")

mAddStatusbar("mMediaTag O1", "o1.tga")
mAddStatusbar("mMediaTag O2", "o2.tga")
mAddStatusbar("mMediaTag O3", "o3.tga")
mAddStatusbar("mMediaTag O4", "o4.tga")
mAddStatusbar("mMediaTag O5", "o5.tga")
mAddStatusbar("mMediaTag O6", "o6.tga")
mAddStatusbar("mMediaTag O7", "o7.tga")
mAddStatusbar("mMediaTag O8", "o8.tga")
mAddStatusbar("mMediaTag O9", "o9.tga")
mAddStatusbar("mMediaTag O10", "o10.tga")
mAddStatusbar("mMediaTag O11", "o11.tga")
mAddStatusbar("mMediaTag O12", "o12.tga")
mAddStatusbar("mMediaTag O13", "o13.tga")
mAddStatusbar("mMediaTag O14", "o14.tga")
mAddStatusbar("mMediaTag O15", "o15.tga")

mAddStatusbar("mMediaTag P1", "p1.tga")
mAddStatusbar("mMediaTag P2", "p2.tga")
mAddStatusbar("mMediaTag P3", "p3.tga")
mAddStatusbar("mMediaTag P4", "p4.tga")
mAddStatusbar("mMediaTag P5", "p5.tga")
mAddStatusbar("mMediaTag P6", "p6.tga")
mAddStatusbar("mMediaTag P7", "p7.tga")
mAddStatusbar("mMediaTag P8", "p8.tga")
mAddStatusbar("mMediaTag P9", "p9.tga")
mAddStatusbar("mMediaTag P10", "p10.tga")
mAddStatusbar("mMediaTag P11", "p11.tga")
mAddStatusbar("mMediaTag P12", "p12.tga")
mAddStatusbar("mMediaTag P13", "p13.tga")
mAddStatusbar("mMediaTag P14", "p14.tga")
mAddStatusbar("mMediaTag P15", "p15.tga")
mAddStatusbar("mMediaTag P16", "p16.tga")
mAddStatusbar("mMediaTag P17", "p17.tga")
mAddStatusbar("mMediaTag P18", "p18.tga")

mAddStatusbar("mMediaTag Q1", "q1.tga")
mAddStatusbar("mMediaTag Q2", "q2.tga")
mAddStatusbar("mMediaTag Q3", "q3.tga")
mAddStatusbar("mMediaTag Q4", "q4.tga")

mAddStatusbar("mMediaTag R1", "r1.tga")
mAddStatusbar("mMediaTag R2", "r2.tga")
mAddStatusbar("mMediaTag R3", "r3.tga")
mAddStatusbar("mMediaTag R4", "r4.tga")
mAddStatusbar("mMediaTag R5", "r5.tga")
mAddStatusbar("mMediaTag R6", "r6.tga")
mAddStatusbar("mMediaTag R7", "r7.tga")
mAddStatusbar("mMediaTag R8", "r8.tga")
mAddStatusbar("mMediaTag R9", "r9.tga")
mAddStatusbar("mMediaTag R10", "r10.tga")
mAddStatusbar("mMediaTag R11", "r11.tga")
mAddStatusbar("mMediaTag R12", "r12.tga")
mAddStatusbar("mMediaTag R13", "r13.tga")
mAddStatusbar("mMediaTag R14", "r14.tga")
mAddStatusbar("mMediaTag R15", "r15.tga")
mAddStatusbar("mMediaTag R16", "r16.tga")
mAddStatusbar("mMediaTag R17", "r17.tga")
mAddStatusbar("mMediaTag R18", "r18.tga")
mAddStatusbar("mMediaTag R19", "r19.tga")
mAddStatusbar("mMediaTag R20", "r20.tga")
mAddStatusbar("mMediaTag R21", "r21.tga")
mAddStatusbar("mMediaTag R22", "r22.tga")
mAddStatusbar("mMediaTag R23", "r23.tga")
mAddStatusbar("mMediaTag R24", "r24.tga")
mAddStatusbar("mMediaTag R25", "r25.tga")
mAddStatusbar("mMediaTag R26", "r26.tga")
mAddStatusbar("mMediaTag R27", "r27.tga")
mAddStatusbar("mMediaTag R28", "r28.tga")
mAddStatusbar("mMediaTag R29", "r29.tga")

mAddStatusbar("mMediaTag Caith UI 1", "Wglass.tga")
mAddStatusbar("mMediaTag Caith UI 2", "Wisps.tga")

mAddStatusbar("MaUIv3", "MaUIv3.tga")

-- Backgrounds
mAddBackground("mMediaTag BG1", "bg1.tga")
mAddBackground("mMediaTag BG2", "bg2.tga")
mAddBackground("mMediaTag BG3", "bg3.tga")
mAddBackground("mMediaTag BG4", "bg4.tga")
mAddBackground("mMediaTag BG5", "bg5.tga")
mAddBackground("mMediaTag BG6", "bg6.tga")
mAddBackground("mMediaTag BG7", "bg7.tga")
mAddBackground("mMediaTag BG8", "bg8.tga")
mAddBackground("mMediaTag BG9", "bg9.tga")
mAddBackground("mMediaTag BG10", "bg10.tga")

mAddBackground("mMediaTag Chat1", "chat1.tga")
mAddBackground("mMediaTag Chat2", "chat2.tga")
mAddBackground("mMediaTag Chat3", "chat3.tga")
mAddBackground("mMediaTag Chat4", "chat4.tga")
mAddBackground("mMediaTag Chat5", "chat5.tga")
mAddBackground("mMediaTag Chat6", "chat6.tga")

mAddBorder("mMediaTag Border1", "mborder1.tga")
mAddBorder("mMediaTag yborder", "yborder.tga")
mAddBorder("mMediaTag yborder2", "yborder2.tga")
mAddBorder("mMediaTag YuluBorderSwitch", "YuluBorderSwitch.tga")
mAddBorder("mMediaTag YuluBorderXI", "YuluBorderXI.tga")

mAddFont("Inter-Bold", "Inter-Bold.ttf")
mAddFont("Inter-Regular", "Inter-Regular.ttf")
mAddFont("Inter-SemiBold", "Inter-SemiBold.ttf")
mAddFont("Lemon-Regular", "Lemon-Regular.ttf")
mAddFont("Oregano-Regular", "Oregano-Regular.ttf")
mAddFont("Oswald-Bold", "Oswald-Bold.ttf")
mAddFont("Oswald-Light", "Oswald-Light.ttf")
mAddFont("Oswald-Regular", "Oswald-Regular.ttf")
mAddFont("Ubuntu-Bold", "Ubuntu-Bold.ttf")
mAddFont("Ubuntu-Medium", "Ubuntu-Medium.ttf")
mAddFont("NotoSans-Bold", "NotoSans-Bold.ttf")
mAddFont("NotoSans-SemiBold", "NotoSans-SemiBold.ttf")
